spring.datasource.url: jdbc:mysql://localhost:3306/tasklib?useSSL=true
spring.datasource.username: root
spring.datasource.password: gbv!b0vgi@%#31IIDi
spring.jpa.hibernate.ddl-auto: create
someParameter:
  value: 5463